### ISSUE TITLE
Cannot get to work with EnVar Plugin

### ISSUE THREAD

**Issue by joedborg** [joncloud/nsis-action#4] opened 2020-05-20 22:40 UTC
Hi there,

I'm trying to get this to work with https://nsis.sourceforge.io/EnVar_plug-in.

The closest I seem to get is:

```yaml
    - name: Download EnVar plugin for NSIS
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: https://nsis.sourceforge.io/mediawiki/images/7/7f/EnVar_plugin.zip
        file-name: envar_plugin.zip
        location: ${{ github.workspace }}
    - name: Extract EnVar plugin
      run: 7z x -o"${{ github.workspace }}/NSIS_Plugins" "${{ github.workspace }}/envar_plugin.zip"
    - name: Create installer
      uses: joncloud/makensis-action@v1.1
      with:
        include-more-plugins: true
        include-custom-plugins-path: ${{ github.workspace }}/NSIS_Plugins/Plugins
        script-file: ${{ github.workspace }}/installer/windows/microk8s.nsi
```

However, it seems the plugin does not pick this up:

```
2020-05-20T22:34:53.9043926Z ##[group]Run joncloud/makensis-action@v1.1
2020-05-20T22:34:53.9044263Z with:
2020-05-20T22:34:53.9044426Z   include-more-plugins: true
2020-05-20T22:34:53.9044541Z   include-custom-plugins-path: d:\a\microk8s\microk8s/NSIS_Plugins/Plugins
2020-05-20T22:34:53.9044663Z   script-file: d:\a\microk8s\microk8s/installer/windows/microk8s.nsi
2020-05-20T22:34:53.9044762Z   just-include: false
2020-05-20T22:34:53.9044866Z env:
2020-05-20T22:34:53.9044980Z   pythonLocation: C:\hostedtoolcache\windows\Python\3.8.3\x64
2020-05-20T22:34:53.9046198Z ##[endgroup]
2020-05-20T22:34:53.9689545Z {
2020-05-20T22:34:53.9690011Z   scriptFile: 'd:\\a\\microk8s\\microk8s/installer/windows/microk8s.nsi',
2020-05-20T22:34:53.9690264Z   justInclude: false,
2020-05-20T22:34:53.9690467Z   includeMorePlugins: true,
2020-05-20T22:34:53.9690675Z   arguments: '',
2020-05-20T22:34:53.9690851Z   includeCustomPluginsPath: ''
2020-05-20T22:34:53.9691039Z }
2020-05-20T22:34:53.9699167Z Running 7z x "-od:\a\_actions\joncloud\makensis-action\v1.1\.nsis" "d:\a\_actions\joncloud\makensis-action\v1.1\nsis\nsis.zip"
2020-05-20T22:34:54.2639643Z includeMorePlugins
2020-05-20T22:34:54.2640521Z copyDirectory d:\a\_actions\joncloud\makensis-action\v1.1\nsis\plugins d:\a\_actions\joncloud\makensis-action\v1.1\.nsis\nsis-3.03\plugins\x86-ansi
2020-05-20T22:34:54.2640806Z copying d:\a\_actions\joncloud\makensis-action\v1.1\nsis\plugins\AccessControl.dll d:\a\_actions\joncloud\makensis-action\v1.1\.nsis\nsis-3.03\plugins\x86-ansi\AccessControl.dll
2020-05-20T22:34:54.2641087Z copying d:\a\_actions\joncloud\makensis-action\v1.1\nsis\plugins\DotNetChecker.dll d:\a\_actions\joncloud\makensis-action\v1.1\.nsis\nsis-3.03\plugins\x86-ansi\DotNetChecker.dll
2020-05-20T22:34:54.2641497Z copying d:\a\_actions\joncloud\makensis-action\v1.1\nsis\plugins\DumpLog.dll d:\a\_actions\joncloud\makensis-action\v1.1\.nsis\nsis-3.03\plugins\x86-ansi\DumpLog.dll
2020-05-20T22:34:54.2641736Z copying d:\a\_actions\joncloud\makensis-action\v1.1\nsis\plugins\FindProcDLL.dll d:\a\_actions\joncloud\makensis-action\v1.1\.nsis\nsis-3.03\plugins\x86-ansi\FindProcDLL.dll
2020-05-20T22:34:54.2747984Z copying d:\a\_actions\joncloud\makensis-action\v1.1\nsis\plugins\KillProcDLL-Url.txt d:\a\_actions\joncloud\makensis-action\v1.1\.nsis\nsis-3.03\plugins\x86-ansi\KillProcDLL-Url.txt
2020-05-20T22:34:54.2769182Z copying d:\a\_actions\joncloud\makensis-action\v1.1\nsis\plugins\KillProcDLL.dll d:\a\_actions\joncloud\makensis-action\v1.1\.nsis\nsis-3.03\plugins\x86-ansi\KillProcDLL.dll
2020-05-20T22:34:54.2770565Z copying d:\a\_actions\joncloud\makensis-action\v1.1\nsis\plugins\services.dll d:\a\_actions\joncloud\makensis-action\v1.1\.nsis\nsis-3.03\plugins\x86-ansi\services.dll
2020-05-20T22:34:54.2772082Z copying d:\a\_actions\joncloud\makensis-action\v1.1\nsis\plugins\Services2.dll d:\a\_actions\joncloud\makensis-action\v1.1\.nsis\nsis-3.03\plugins\x86-ansi\Services2.dll
2020-05-20T22:34:54.2820014Z copying d:\a\_actions\joncloud\makensis-action\v1.1\nsis\plugins\SimpleSC.dll d:\a\_actions\joncloud\makensis-action\v1.1\.nsis\nsis-3.03\plugins\x86-ansi\SimpleSC.dll
2020-05-20T22:34:54.2821205Z copying d:\a\_actions\joncloud\makensis-action\v1.1\nsis\plugins\ToolTips.dll d:\a\_actions\joncloud\makensis-action\v1.1\.nsis\nsis-3.03\plugins\x86-ansi\ToolTips.dll
2020-05-20T22:34:54.2844758Z copying d:\a\_actions\joncloud\makensis-action\v1.1\nsis\plugins\UserMgr.dll d:\a\_actions\joncloud\makensis-action\v1.1\.nsis\nsis-3.03\plugins\x86-ansi\UserMgr.dll
2020-05-20T22:34:54.2845322Z Time taken (Unzip): 313 millisecond(s)
2020-05-20T22:34:54.2846338Z Running d:\a\_actions\joncloud\makensis-action\v1.1\.nsis\nsis-3.03\makensis.exe /V1  "d:\a\microk8s\microk8s\installer\windows\microk8s.nsi"
2020-05-20T22:34:56.3748014Z Plugin not found, cannot call EnVar::AddValue
2020-05-20T22:34:56.3748527Z Error in script "d:\a\microk8s\microk8s\installer\windows\microk8s.nsi" on line 83 -- aborting creation process
2020-05-20T22:34:56.3754129Z ##[error]Command failed: d:\a\_actions\joncloud\makensis-action\v1.1\.nsis\nsis-3.03\makensis.exe /V1  "d:\a\microk8s\microk8s\installer\windows\microk8s.nsi"
Plugin not found, cannot call EnVar::AddValue
Error in script "d:\a\microk8s\microk8s\installer\windows\microk8s.nsi" on line 83 -- aborting creation process

2020-05-20T22:34:56.3980896Z Post job cleanup.
2020-05-20T22:34:58.4882507Z [command]"C:\Program Files\Git\bin\git.exe" version
2020-05-20T22:34:58.5090591Z git version 2.26.2.windows.1
2020-05-20T22:34:58.5161022Z [command]"C:\Program Files\Git\bin\git.exe" config --local --name-only --get-regexp core\.sshCommand
2020-05-20T22:34:58.5426451Z [command]"C:\Program Files\Git\bin\git.exe" submodule foreach --recursive "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
2020-05-20T22:34:59.0873014Z [command]"C:\Program Files\Git\bin\git.exe" config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2020-05-20T22:34:59.1082963Z http.https://github.com/.extraheader
2020-05-20T22:34:59.1128192Z [command]"C:\Program Files\Git\bin\git.exe" config --local --unset-all http.https://github.com/.extraheader
2020-05-20T22:34:59.1392832Z [command]"C:\Program Files\Git\bin\git.exe" submodule foreach --recursive "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
2020-05-20T22:34:59.6616192Z Cleaning up orphan processes
```

Thanks,
Joe

**Comment by joncloud** [comment] 2020-05-21 02:29
I've been able to reproduce this in my test project [makensis-action-test](https://github.com/joncloud/makensis-action-test/runs/695047764).

**Comment by joncloud** [comment] 2020-05-21 02:42
I found a typo in one of the variable names, and pushed an updated release. This is resolved in the latest action in [makensis-action-test ](https://github.com/joncloud/makensis-action-test/runs/695064611) with 20319a909ed90ff5405bbec9d65b720ba6763568. For comparison, I also had to adjust the value of `include-custom-plugins-path` in the [latest commit](https://github.com/joncloud/makensis-action-test/commit/8f2ab0878ca6b2a57deba674ae2c57f28d3bb7f5).

Let me know if you have any additional issues. If you link to a repo, then I can try and help diagnose any further problems.

**Comment by joedborg** [comment] 2020-05-21 14:38
Hey @joncloud, thanks for the quick response!  I've updated mine, but still seem to be hitting an issue:  https://github.com/ubuntu/microk8s/pull/1213/checks?check_run_id=696573069 https://github.com/ubuntu/microk8s/pull/1213/commits/9f00e0722b51faec65176186666503a92c6f00f6

Can you see what I'm doing wrong?

Thanks again for your time.

**Comment by joedborg** [comment] 2020-05-21 14:44
My guess is that the EnVar plugin requires more than just being extracted into Plugins; it also needs to be extracted into Contrib.  Would it be possible to extract this zip into `_actions\joncloud\makensis-action\v1.2\nsis\` first?

**Comment by joncloud** [comment] 2020-05-21 15:17
Let me tinker around a bit with this. I ported the spec that was defined for the Azure DevOps marketplace, and I think we can do some tuning to make it a little bit more user friendly.

**Comment by joedborg** [comment] 2020-05-21 15:24
Thanks!

**Comment by joncloud** [comment] 2020-05-21 15:37
It looks like the issue is that the plugins are only being to/from `x86-ansi`, but your project needs to ensure that the `x86-unicode` plugin is also copied. I should be able to whip something up to get this working.

**Comment by joncloud** [comment] 2020-05-21 16:49
I just created v2.0 with a new API spec. I think this should be a little more usable when you need to use plugins beyond `x86-ansi`. I updated the [sample project](https://github.com/joncloud/makensis-action-test/commit/a38594c94b9397bb662ab84b98d77fcf8ec8cb92).

**Comment by joncloud** [comment] 2020-06-12 03:32
If you have any issues with the new implementation, feel free to reopen this issue.

**Closed as completed by joncloud** 2020-06-12 03:32 UTC
